export let pantryItems = [
  {
    id: 1,
    name: "Milk",
    expiryDate: new Date(2020, 10, 15),
  },
  {
    id: 2,
    name: "Banana",
    expiryDate: new Date(2020, 10, 20),
  },
  {
    id: 3,
    name: "Chicken",
    expiryDate: new Date(2020, 11, 30),
  },
  {
    id: 4,
    name: "Rice",
    expiryDate: new Date(2020, 11, 15),
  },
];

export let groceryListItems = [
  {
    id: 1,
    name: "Flour",
    checked: false,
  },
  {
    id: 2,
    name: "Cheese",
    checked: false,
  },
  {
    id: 3,
    name: "Milk",
    checked: false,
  },
  {
    id: 4,
    name: "Tomatoes",
    checked: false,
  },
];

export const recipes = [
  {
    id: 975012,
    title: "Brown Rice Breakfast Porridge",
    image: "https://spoonacular.com/recipeImages/975012-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 1,
    missedIngredients: [
      {
        id: 11424,
        amount: 2.0,
        unit: "Tbsp",
        unitLong: "Tbsps",
        unitShort: "Tbsp",
        aisle: "Baking",
        name: "pumpkin puree",
        original: "2 Tbsp pumpkin puree",
        originalString: "2 Tbsp pumpkin puree",
        originalName: "pumpkin puree",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/pumpkin-puree.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9040,
        amount: 2.0,
        unit: "Tbsp",
        unitLong: "Tbsps",
        unitShort: "Tbsp",
        aisle: "Produce",
        name: "banana",
        original: "2 Tbsp mashed banana",
        originalString: "2 Tbsp mashed banana",
        originalName: "mashed banana",
        metaInformation: ["mashed"],
        meta: ["mashed"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/bananas.jpg",
      },
      {
        id: 10020048,
        amount: 1.0,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Pasta and Rice",
        name: "brown minute rice",
        original: "1 cup Minute Ready to Serve Brown Rice",
        originalString: "1 cup Minute Ready to Serve Brown Rice",
        originalName: "Minute Ready to Serve Brown Rice",
        metaInformation: ["ready to serve"],
        meta: ["ready to serve"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/uncooked-brown-rice.png",
      },
      {
        id: 1077,
        amount: 2.0,
        unit: "Tbsp",
        unitLong: "Tbsps",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "2-3 Tbsp almond, coconut or cow's milk, warmed",
        originalString: "2-3 Tbsp almond, coconut or cow's milk, warmed",
        originalName: "almond, coconut or cow's milk, warmed",
        metaInformation: ["warmed"],
        meta: ["warmed"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 5006,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Meat",
        name: "chicken",
        original: "chicken",
        originalString: "chicken",
        originalName: "chicken",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg",
      },
      {
        id: 20444,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Pasta and Rice",
        name: "rice",
        original: "rice",
        originalString: "rice",
        originalName: "rice",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/uncooked-white-rice.png",
      },
    ],
    likes: 1,
  },
  {
    id: 399726,
    title: "Skillet Fried Chicken with Black Pepper Gravy",
    image: "https://spoonacular.com/recipeImages/399726-312x231.jpeg",
    imageType: "jpeg",
    usedIngredientCount: 3,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 2031,
        amount: 0.25,
        unit: "teaspoon",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Spices and Seasonings",
        name: "cayenne pepper",
        original: "1/4 teaspoon cayenne pepper, or to taste",
        originalString: "1/4 teaspoon cayenne pepper, or to taste",
        originalName: "cayenne pepper, or to taste",
        metaInformation: ["to taste"],
        meta: ["to taste"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/chili-powder.jpg",
      },
      {
        id: 6172,
        amount: 1.0,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Canned and Jarred",
        name: "chicken stock",
        original:
          "1 cup homemade chicken stock, reduced-fat low-sodium chicken broth or water",
        originalString:
          "1 cup homemade chicken stock, reduced-fat low-sodium chicken broth or water",
        originalName:
          "homemade chicken stock, reduced-fat low-sodium chicken broth or water",
        metaInformation: ["low-sodium", "homemade", "reduced-fat"],
        meta: ["low-sodium", "homemade", "reduced-fat"],
        extendedName: "low fat chicken stock",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/chicken-broth.png",
      },
    ],
    usedIngredients: [
      {
        id: 1082,
        amount: 1.0,
        unit: "cup",
        unitLong: "cup",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "1 percent milk",
        original: "1 cup whole or 2-percent milk",
        originalString: "1 cup whole or 2-percent milk",
        originalName: "whole or 2-percent milk",
        metaInformation: ["whole"],
        meta: ["whole"],
        extendedName: "whole 1 percent milk",
        image: "https://spoonacular.com/cdn/ingredients_100x100/milk.png",
      },
      {
        id: 5006,
        amount: 2.0,
        unit: "pound",
        unitLong: "pounds",
        unitShort: "lb",
        aisle: "Meat",
        name: "chicken",
        original: "1 2- to 2 1/2-pound chicken, cut into 8 pieces",
        originalString: "1 2- to 2 1/2-pound chicken, cut into 8 pieces",
        originalName: "chicken, cut into 8 pieces",
        metaInformation: ["cut into 8 pieces"],
        meta: ["cut into 8 pieces"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg",
      },
      {
        id: 10220445,
        amount: 6.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Pasta and Rice",
        name: "cooked rice",
        original: "Cooked rice, for serving",
        originalString: "Cooked rice, for serving",
        originalName: "Cooked rice, for serving",
        metaInformation: ["cooked", "for serving"],
        meta: ["cooked", "for serving"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/uncooked-white-rice.png",
      },
    ],
    unusedIngredients: [
      {
        id: 1077,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "milk",
        originalString: "milk",
        originalName: "milk",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/milk.png",
      },
      {
        id: 9040,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "banana",
        original: "banana",
        originalString: "banana",
        originalName: "banana",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/bananas.jpg",
      },
      {
        id: 20444,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Pasta and Rice",
        name: "rice",
        original: "rice",
        originalString: "rice",
        originalName: "rice",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/uncooked-white-rice.png",
      },
    ],
    likes: 18,
  },
  {
    id: 921334,
    title: "Savory Rice Porridge #SundaySupper",
    image: "https://spoonacular.com/recipeImages/921334-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 3,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 1017,
        amount: 4.0,
        unit: "ounces",
        unitLong: "ounces",
        unitShort: "oz",
        aisle: "Cheese",
        name: "cream cheese",
        original: "4 ounces cream cheese",
        originalString: "4 ounces cream cheese",
        originalName: "cream cheese",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/cream-cheese.jpg",
      },
      {
        id: 2043,
        amount: 3.0,
        unit: "teaspoons",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Spices and Seasonings",
        name: "ground turmeric",
        original: "3 teaspoons ground turmeric",
        originalString: "3 teaspoons ground turmeric",
        originalName: "ground turmeric",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/turmeric.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 5006,
        amount: 4.0,
        unit: "servings",
        unitLong: "servings",
        unitShort: "servings",
        aisle: "Meat",
        name: "chicken",
        original: "Toppings like chicken, pork, beef, fish, eggs, or lettuce",
        originalString:
          "Toppings like chicken, pork, beef, fish, eggs, or lettuce",
        originalName:
          "Toppings like chicken, pork, beef, fish, eggs, or lettuce",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg",
      },
      {
        id: 10220445,
        amount: 2.0,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Pasta and Rice",
        name: "cooked rice",
        original: "2 cups cooked rice, hot",
        originalString: "2 cups cooked rice, hot",
        originalName: "cooked rice, hot",
        metaInformation: ["hot", "cooked"],
        meta: ["hot", "cooked"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/uncooked-white-rice.png",
      },
      {
        id: 1077,
        amount: 2.0,
        unit: "tablespoons",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "2 tablespoons milk",
        originalString: "2 tablespoons milk",
        originalName: "milk",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/milk.png",
      },
    ],
    unusedIngredients: [
      {
        id: 9040,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "banana",
        original: "banana",
        originalString: "banana",
        originalName: "banana",
        metaInformation: [],
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/bananas.jpg",
      },
      {
        id: 20444,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Pasta and Rice",
        name: "rice",
        original: "rice",
        originalString: "rice",
        originalName: "rice",
        metaInformation: [],
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/uncooked-white-rice.png",
      },
    ],
    likes: 0,
  },
];
